### ISSUE TITLE
Adjust Discord Banner CSS

### ISSUE THREAD

**Issue by naomieow** [Stardust-Labs-MC/wiki#38]
Adjust Discord Banner CSS to be to our overlord Tera's liking
![image](https://github.com/Stardust-Labs-MC/wiki/assets/79906167/9f34f687-409b-4a56-ba90-f133f4e73683)

**Comment by Tera458** [comment]
Note that depending on if the toolbox on the left is hidden or not, the size available for the banner is different

**Comment by Tera458** [comment]
Also add lightmode invert or smth
